// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSkFIOtIGvc_g0U-8HDF5RoYHVG1TLyY',
    appId: '1:108435792034:web:cf3fbe73b7fbb349deb7fb',
    messagingSenderId: '108435792034',
    projectId: 'mygameapp-fcf45',
    authDomain: 'mygameapp-fcf45.firebaseapp.com',
    storageBucket: 'mygameapp-fcf45.firebasestorage.app',
    measurementId: 'G-3VETK8CH5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZk-0knR8CmRf3GAY3nyYan0ozB7ShE48',
    appId: '1:108435792034:android:86431f9a4fd7640cdeb7fb',
    messagingSenderId: '108435792034',
    projectId: 'mygameapp-fcf45',
    storageBucket: 'mygameapp-fcf45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FvhMMFhrzlPiGDZg4XT5a51NbcII0WA',
    appId: '1:108435792034:ios:20e2a618a9868706deb7fb',
    messagingSenderId: '108435792034',
    projectId: 'mygameapp-fcf45',
    storageBucket: 'mygameapp-fcf45.firebasestorage.app',
    iosBundleId: 'com.example.myGameApp',
  );
}
